\set ON_ERROR_STOP on
SELECT public.test_assert((SELECT count(*)=0 FROM private.push_events),'no historical events backfilled');
SELECT public.test_assert((SELECT count(*)=1 FROM cron.job WHERE jobname='dispatch-parent-push'),'cron installed once');
SELECT public.test_assert(NOT has_function_privilege('anon','public.get_my_push_preferences()','EXECUTE'),'anon cannot read preference RPC');
SELECT public.test_assert(NOT has_function_privilege('authenticated','public.claim_push_deliveries(integer)','EXECUTE'),'parents cannot dispatch');
SELECT public.test_assert((SELECT bool_and(relrowsecurity) FROM pg_class WHERE oid IN ('public.push_devices'::regclass,'public.push_preferences'::regclass,'private.push_events'::regclass,'private.push_deliveries'::regclass)),'new tables have RLS');
SET ROLE authenticated;
SELECT public.test_actor(1);
SELECT public.test_assert(public.get_my_push_preferences()='{"enabled":false}','new account defaults off');
SELECT public.test_denied($s$SELECT public.register_push_device(public.test_uuid(201),public.test_uuid(301),'parent-one-token-abcdefghijklmnopqrstuvwxyz')$s$,'registration requires opt in');
SELECT public.test_assert(public.set_my_push_enabled(true)='{"enabled":true}','opt in saved');
SELECT public.register_push_device(public.test_uuid(201),public.test_uuid(301),'parent-one-token-abcdefghijklmnopqrstuvwxyz');
SELECT public.register_push_device(public.test_uuid(201),public.test_uuid(301),'parent-one-token-refreshed-abcdefghijklmnopqrstuvwxyz');
SELECT public.test_assert((SELECT count(*)=1 FROM public.push_devices),'own device metadata visible');
SELECT public.test_denied('SELECT token FROM public.push_devices','raw token cannot be selected');
SELECT public.test_denied('UPDATE public.push_preferences SET enabled=false','direct preference writes denied');
SELECT public.test_denied('INSERT INTO private.push_events(source_type,source_id) VALUES (''course'',gen_random_uuid())','client cannot create event');
SELECT public.test_actor(2);
SELECT public.test_assert((SELECT count(*)=0 FROM public.push_devices),'other parents cannot see devices');
SELECT public.set_my_push_enabled(true);
SELECT public.register_push_device(public.test_uuid(202),public.test_uuid(302),'parent-two-token-abcdefghijklmnopqrstuvwxyz');
SELECT public.revoke_push_device(public.test_uuid(301));
SELECT public.test_actor(3);
SELECT public.set_my_push_enabled(true);
SELECT public.register_push_device(public.test_uuid(203),public.test_uuid(303),'parent-three-token-abcdefghijklmnopqrstuvwxyz');
SELECT public.test_actor(4);
SELECT public.set_my_push_enabled(true);
SELECT public.register_push_device(public.test_uuid(204),public.test_uuid(304),'parent-four-token-abcdefghijklmnopqrstuvwxyz');
SELECT public.test_actor(5);
SELECT public.test_denied('SELECT public.set_my_push_enabled(true)','coach cannot enable parent push');
SELECT public.test_actor(6);
SELECT public.test_denied('SELECT public.set_my_push_enabled(true)','disabled parent denied');
SELECT public.test_actor(1,102);
SELECT public.test_denied('SELECT public.get_my_push_preferences()','another users session denied');
SELECT public.test_actor(1,999);
SELECT public.test_denied('SELECT public.get_my_push_preferences()','missing session denied');
RESET ROLE;
SELECT public.test_assert((SELECT revoked_at IS NULL FROM public.push_devices WHERE id=public.test_uuid(301)),'cross-user revoke leaves device enabled');
UPDATE auth.sessions SET not_after=now()-interval '1 second' WHERE id=public.test_uuid(101);
SET ROLE authenticated;
SELECT public.test_actor(1);
SELECT public.test_denied('SELECT public.get_my_push_preferences()','expired session denied');
RESET ROLE;
UPDATE auth.sessions SET not_after=NULL WHERE id=public.test_uuid(101);

INSERT INTO public.course_announcements(id,course_id,content) VALUES(public.test_uuid(51),public.test_uuid(11),'Private content must not leave database');
DO $$ DECLARE c JSONB; p JSONB; BEGIN
    c:=public.claim_push_deliveries(20);
    PERFORM public.test_assert(jsonb_array_length(c)=1,'course announcement one delivery despite two children');
    p:=public.prepare_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID);
    PERFORM public.test_assert(p->'data'->>'bindingId'=public.test_uuid(301)::TEXT,'course audience excludes other club and pending enrollment');
    PERFORM public.test_assert(p->'data'->>'path'='/account/announcements','announcement route exact');
    PERFORM public.test_assert(p::TEXT NOT LIKE '%Private content%','private announcement not in payload');
    PERFORM public.test_assert(p->'data'->>'expiresAt' ~ '^[0-9]{13}$','expiry epoch milliseconds string');
    PERFORM public.test_assert(jsonb_array_length(public.claim_push_deliveries(20))=0,'live lease prevents duplicate claim');
    PERFORM public.finish_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID,'sent','FCM_ACCEPTED');
END $$;
UPDATE public.course_announcements SET pinned=true,content='Edited' WHERE id=public.test_uuid(51);
SELECT public.test_assert(jsonb_array_length(public.claim_push_deliveries(20))=0,'pin or edit does not resend announcement');
UPDATE public.course_announcements SET content='Old update' WHERE id=public.test_uuid(50);
UPDATE public.courses SET active=false WHERE id=public.test_uuid(11);
UPDATE public.courses SET active=true WHERE id=public.test_uuid(11);
SELECT public.test_assert((SELECT count(*)=1 FROM private.push_events),'historical edits do not manufacture events');

INSERT INTO public.club_announcements(id,club_id,audience_kind,audience_id) VALUES(public.test_uuid(52),public.test_uuid(10),'CAMP',public.test_uuid(13));
DO $$ DECLARE c JSONB;p JSONB;BEGIN
 c:=public.claim_push_deliveries();p:=public.prepare_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID);
 PERFORM public.test_assert(jsonb_array_length(c)=1 AND p->'data'->>'bindingId'=public.test_uuid(303)::TEXT,'camp targeted announcement reaches enrolled parent only');
 PERFORM public.finish_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID,'sent');END $$;
INSERT INTO public.club_announcements(id,club_id,publish_at) VALUES(public.test_uuid(53),public.test_uuid(10),now()+interval '1 hour');
SELECT public.test_assert(jsonb_array_length(public.claim_push_deliveries())=0,'scheduled announcement waits');
UPDATE public.club_announcements SET publish_at=now()-interval '1 second' WHERE id=public.test_uuid(53);
DO $$ DECLARE c JSONB;BEGIN c:=public.claim_push_deliveries();
 PERFORM public.test_assert(jsonb_array_length(c)=2,'general club announcement includes course and camp members');
 UPDATE public.club_announcements SET is_active=false WHERE id=public.test_uuid(53);
 PERFORM public.test_assert(public.prepare_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID) IS NULL,'hidden announcement revalidated before send');
 PERFORM public.test_assert(public.prepare_push_delivery((c->1->>'deliveryId')::UUID,(c->1->>'leaseId')::UUID) IS NULL,'hidden event skips every recipient'); END $$;
INSERT INTO public.club_announcements(id,club_id,expires_at) VALUES(public.test_uuid(54),public.test_uuid(10),now()-interval '1 second');
SELECT public.test_assert(jsonb_array_length(public.claim_push_deliveries())=0,'expired announcement never delivered');
INSERT INTO public.club_announcements(id,club_id,audience_kind,audience_id) VALUES(public.test_uuid(55),public.test_uuid(20),'CAMP',public.test_uuid(13));
SELECT public.test_assert(jsonb_array_length(public.claim_push_deliveries())=0,'mismatched club ownership cannot leak announcement');

BEGIN;
INSERT INTO public.attendance(id,occurrence_id,child_id,status) VALUES(public.test_uuid(60),public.test_uuid(40),public.test_uuid(31),'PRESENT');
ROLLBACK;
SELECT public.test_assert((SELECT count(*)=0 FROM private.push_events WHERE source_type='attendance'),'rolled back attendance creates no event');
INSERT INTO public.attendance(id,occurrence_id,child_id,status) VALUES(public.test_uuid(60),public.test_uuid(40),public.test_uuid(31),'PRESENT');
UPDATE public.attendance SET status='PRESENT',note='Sensitive note' WHERE id=public.test_uuid(60);
SELECT public.test_assert((SELECT count(*)=1 FROM private.push_events WHERE source_type='attendance'),'identical status and note edit do not duplicate');
DO $$ DECLARE c JSONB;BEGIN c:=public.claim_push_deliveries();
 PERFORM public.test_assert(jsonb_array_length(c)=1,'attendance reaches only child parent');
 UPDATE public.attendance SET status='ABSENT' WHERE id=public.test_uuid(60);
 PERFORM public.test_assert(public.prepare_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID) IS NULL,'changed attendance cancels earlier lease'); END $$;
DO $$ DECLARE c JSONB;p JSONB;BEGIN c:=public.claim_push_deliveries();p:=public.prepare_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID);
 PERFORM public.test_assert(jsonb_array_length(c)=1 AND p->'data'->>'path'='/account/attendance','changed status emits one current generic attendance notification');
 DELETE FROM public.attendance WHERE id=public.test_uuid(60);
 PERFORM public.test_assert(public.prepare_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID) IS NULL,'cleared attendance cancels pending notice'); END $$;

INSERT INTO public.courses(id,club_id,active) VALUES(public.test_uuid(70),public.test_uuid(10),false);
SELECT public.test_assert(jsonb_array_length(public.claim_push_deliveries())=0,'new inactive course waits for publication');
SELECT public.test_assert(NOT EXISTS(SELECT FROM private.push_events WHERE source_type='course' AND source_id=public.test_uuid(70)),'inactive course creates no unbounded dormant event');
UPDATE public.courses SET active=true WHERE id=public.test_uuid(70);
DO $$ DECLARE c JSONB;p JSONB;i JSONB;BEGIN c:=public.claim_push_deliveries();
 PERFORM public.test_assert(jsonb_array_length(c)=2,'first course activation reaches current club parents');
 FOR i IN SELECT * FROM jsonb_array_elements(c) LOOP
 p:=public.prepare_push_delivery((i->>'deliveryId')::UUID,(i->>'leaseId')::UUID);
 PERFORM public.test_assert(p->'data'->>'path'='/cursuri/'||public.test_uuid(70)::TEXT,'course route binds entity UUID');
 PERFORM public.finish_push_delivery((i->>'deliveryId')::UUID,(i->>'leaseId')::UUID,'sent');END LOOP;END $$;
UPDATE public.courses SET active=false WHERE id=public.test_uuid(70);
UPDATE public.courses SET active=true WHERE id=public.test_uuid(70);
SELECT public.test_assert(jsonb_array_length(public.claim_push_deliveries())=0,'reactivation does not republish old course');
INSERT INTO public.courses(id,club_id,active) VALUES(public.test_uuid(100),NULL,true);
SELECT public.test_assert(NOT EXISTS(SELECT FROM private.push_events WHERE source_type='course' AND source_id=public.test_uuid(100)),'active independent course has no club publication yet');
UPDATE public.courses SET club_id=public.test_uuid(10) WHERE id=public.test_uuid(100);
DO $$ DECLARE c JSONB;p JSONB;i JSONB;BEGIN c:=public.claim_push_deliveries();
 PERFORM public.test_assert(jsonb_array_length(c)=2,'null to club publishes first eligible active course');
 FOR i IN SELECT * FROM jsonb_array_elements(c) LOOP
 p:=public.prepare_push_delivery((i->>'deliveryId')::UUID,(i->>'leaseId')::UUID);
 PERFORM public.test_assert(p->'data'->>'path'='/cursuri/'||public.test_uuid(100)::TEXT,'null to club publication routes to new course');
 PERFORM public.finish_push_delivery((i->>'deliveryId')::UUID,(i->>'leaseId')::UUID,'sent');END LOOP;END $$;
INSERT INTO public.courses(id,club_id,active) VALUES(public.test_uuid(110),public.test_uuid(10),false);
UPDATE public.courses SET club_id=public.test_uuid(20) WHERE id=public.test_uuid(110);
UPDATE public.courses SET active=true WHERE id=public.test_uuid(110);
DO $$ DECLARE c JSONB;p JSONB;BEGIN c:=public.claim_push_deliveries();p:=public.prepare_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID);
 PERFORM public.test_assert(jsonb_array_length(c)=1 AND p->'data'->>'bindingId'=public.test_uuid(302)::TEXT,'draft moved from club A to B notifies only current club B');
 PERFORM public.finish_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID,'sent');END $$;
UPDATE public.courses SET active=true WHERE id=public.test_uuid(12);
DO $$ DECLARE c JSONB;i JSONB;BEGIN c:=public.claim_push_deliveries();
 PERFORM public.test_assert(jsonb_array_length(c)=2,'pre-migration inactive draft first activated now is published');
 FOR i IN SELECT * FROM jsonb_array_elements(c) LOOP
 PERFORM public.prepare_push_delivery((i->>'deliveryId')::UUID,(i->>'leaseId')::UUID);
 PERFORM public.finish_push_delivery((i->>'deliveryId')::UUID,(i->>'leaseId')::UUID,'sent');END LOOP;END $$;
UPDATE private.push_events SET expires_at=now()-interval '40 days' WHERE source_type='course' AND source_id=public.test_uuid(70);
SELECT private.invoke_push_dispatch();
UPDATE public.courses SET active=false WHERE id=public.test_uuid(70);
UPDATE public.courses SET active=true WHERE id=public.test_uuid(70);
SELECT public.test_assert(NOT EXISTS(SELECT FROM private.push_events WHERE source_type='course' AND source_id=public.test_uuid(70)),'retention cleanup cannot reset durable first-publication marker');
SELECT public.test_assert(EXISTS(SELECT FROM private.push_course_publications WHERE id=public.test_uuid(70)),'published course retains one bounded lifetime marker');
INSERT INTO public.camps(id,club_id,slug,period_end) VALUES(public.test_uuid(71),public.test_uuid(10),'--tabara--',current_date+1);
DO $$ DECLARE c JSONB;p JSONB;i JSONB;BEGIN c:=public.claim_push_deliveries();
 PERFORM public.test_assert(jsonb_array_length(c)=2,'camp insert reaches current club parents');
 FOR i IN SELECT * FROM jsonb_array_elements(c) LOOP
 p:=public.prepare_push_delivery((i->>'deliveryId')::UUID,(i->>'leaseId')::UUID);
 PERFORM public.test_assert(p->'data'->>'path'='/tabere/--tabara--','valid existing camp slug semantics preserved');
 PERFORM public.finish_push_delivery((i->>'deliveryId')::UUID,(i->>'leaseId')::UUID,'sent');END LOOP;END $$;
INSERT INTO public.camps(id,club_id,slug,period_end) VALUES(public.test_uuid(72),NULL,'independent',current_date+1);
SELECT public.test_assert(jsonb_array_length(public.claim_push_deliveries())=0,'independent coach camp has no inferred club audience');

INSERT INTO public.course_announcements(id,course_id) VALUES(public.test_uuid(80),public.test_uuid(11));
DO $$ DECLARE c JSONB;BEGIN c:=public.claim_push_deliveries();
 UPDATE public.enrollments SET status='CANCELLED' WHERE child_id IN(public.test_uuid(31),public.test_uuid(34));
 PERFORM public.test_assert(public.prepare_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID) IS NULL,'withdrawal after claim blocks send');END $$;
UPDATE public.enrollments SET status='ACTIVE' WHERE child_id IN(public.test_uuid(31),public.test_uuid(34));
INSERT INTO public.course_announcements(id,course_id) VALUES(public.test_uuid(81),public.test_uuid(11));
DO $$ DECLARE c JSONB;BEGIN c:=public.claim_push_deliveries();
 DELETE FROM auth.sessions WHERE id=public.test_uuid(101);
 PERFORM public.test_assert(public.prepare_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID) IS NULL,'deleted auth session blocks send despite device record');END $$;
SET ROLE authenticated;
SELECT public.test_actor(1);
SELECT public.test_denied($s$SELECT public.register_push_device(public.test_uuid(201),public.test_uuid(301),'parent-one-token-abcdefghijklmnopqrstuvwxyz')$s$,'old JWT cannot restore missing session');
SELECT public.revoke_push_device(public.test_uuid(301));
RESET ROLE;
INSERT INTO auth.sessions VALUES(public.test_uuid(101),public.test_uuid(1),NULL);
SET ROLE authenticated;
SELECT public.test_actor(1);
SELECT public.test_denied($s$SELECT public.register_push_device(public.test_uuid(201),public.test_uuid(301),'parent-one-token-abcdefghijklmnopqrstuvwxyz')$s$,'revoked binding cannot be reused');
SELECT public.revoke_push_device(public.test_uuid(399));
SELECT public.test_denied($s$SELECT public.register_push_device(public.test_uuid(201),public.test_uuid(399),'parent-one-token-abcdefghijklmnopqrstuvwxyz')$s$,'revoke receipt wins against delayed first registration');
SELECT public.register_push_device(public.test_uuid(201),public.test_uuid(311),'parent-one-token-abcdefghijklmnopqrstuvwxyz');
SELECT public.set_my_push_enabled(false);
RESET ROLE;
SELECT public.test_assert((SELECT revoked_at IS NOT NULL FROM public.push_devices WHERE id=public.test_uuid(311)),'global opt out revokes binding');
SET ROLE authenticated;
SELECT public.test_actor(1);
SELECT public.set_my_push_enabled(true);
SELECT public.register_push_device(public.test_uuid(201),public.test_uuid(321),'parent-one-token-abcdefghijklmnopqrstuvwxyz');
SELECT public.test_actor(2);
SELECT public.register_push_device(public.test_uuid(201),public.test_uuid(322),'parent-one-token-abcdefghijklmnopqrstuvwxyz');
RESET ROLE;
SELECT public.test_assert((SELECT revoked_at IS NOT NULL FROM public.push_devices WHERE id=public.test_uuid(321)),'shared installation and token transfer revokes previous account');
SELECT public.test_assert((SELECT count(*)=1 FROM public.push_devices WHERE installation_id=public.test_uuid(201) AND revoked_at IS NULL),'one installation has one active binding');
SET ROLE authenticated;
SELECT public.test_actor(1);
SELECT public.register_push_device(public.test_uuid(201),public.test_uuid(331),'parent-one-token-final-abcdefghijklmnopqrstuvwxyz');
RESET ROLE;

INSERT INTO public.course_announcements(id,course_id) VALUES(public.test_uuid(82),public.test_uuid(11));
DO $$ DECLARE c JSONB;p JSONB;v_id UUID;v_old UUID;v_new UUID;BEGIN c:=public.claim_push_deliveries();v_id:=(c->0->>'deliveryId')::UUID;v_old:=(c->0->>'leaseId')::UUID;
 UPDATE private.push_deliveries SET lease_until=now()-interval '1 second' WHERE id=v_id;
 c:=public.claim_push_deliveries();v_new:=(c->0->>'leaseId')::UUID;
 PERFORM public.test_assert(v_new<>v_old,'expired lease can be reclaimed with fresh identity');
 PERFORM public.test_assert(public.prepare_push_delivery(v_id,v_old) IS NULL,'stale lease cannot prepare');
 PERFORM public.finish_push_delivery(v_id,v_old,'sent');
 PERFORM public.test_assert((SELECT state='sending' FROM private.push_deliveries WHERE id=v_id),'stale completion cannot settle new claim');
 p:=public.prepare_push_delivery(v_id,v_new);
 PERFORM public.finish_push_delivery(v_id,v_new,'retry','FCM_UNAVAILABLE',300);
 PERFORM public.test_assert((SELECT state='pending' AND available_at>=now()+interval '299 seconds' FROM private.push_deliveries WHERE id=v_id),'retry obeys bounded retry-after');
 UPDATE private.push_deliveries SET attempts=4,available_at=now() WHERE id=v_id;
 c:=public.claim_push_deliveries();p:=public.prepare_push_delivery(v_id,(c->0->>'leaseId')::UUID);
 PERFORM public.finish_push_delivery(v_id,(c->0->>'leaseId')::UUID,'retry','FCM_UNAVAILABLE');
 PERFORM public.test_assert((SELECT state='dead' AND attempts=5 FROM private.push_deliveries WHERE id=v_id),'fifth failed attempt dead letters');END $$;
INSERT INTO public.course_announcements(id,course_id) VALUES(public.test_uuid(83),public.test_uuid(11));
DO $$ DECLARE c JSONB;p JSONB;BEGIN c:=public.claim_push_deliveries();p:=public.prepare_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID);
 UPDATE public.push_devices SET token='rotated-token-abcdefghijklmnopqrstuvwxyz' WHERE id=public.test_uuid(331);
 PERFORM public.finish_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID,'invalid_token','FCM_UNREGISTERED');
 PERFORM public.test_assert((SELECT revoked_at IS NULL FROM public.push_devices WHERE id=public.test_uuid(331)),'invalid old token does not revoke a newly rotated token');END $$;
INSERT INTO public.course_announcements(id,course_id) VALUES(public.test_uuid(84),public.test_uuid(11));
DO $$ DECLARE c JSONB;p JSONB;BEGIN c:=public.claim_push_deliveries();p:=public.prepare_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID);
 PERFORM public.finish_push_delivery((c->0->>'deliveryId')::UUID,(c->0->>'leaseId')::UUID,'invalid_token','FCM_UNREGISTERED');
 PERFORM public.test_assert((SELECT revoked_at IS NOT NULL FROM public.push_devices WHERE id=public.test_uuid(331)),'invalid current token revokes device');END $$;
SELECT private.invoke_push_dispatch();
SELECT public.test_assert((SELECT count(*)=0 FROM public.test_network_calls),'missing dispatch secret performs no network request');
INSERT INTO private.push_events(source_type,source_id,expires_at) SELECT 'attendance',gen_random_uuid(),now()-interval '40 days' FROM generate_series(1,501);
INSERT INTO public.push_devices(id,installation_id,user_id,session_id,token,revoked_at,updated_at) VALUES(public.test_uuid(900),public.test_uuid(901),public.test_uuid(1),public.test_uuid(101),'stale-device-token-abcdefghijklmnopqrstuvwxyz',now()-interval '40 days',now()-interval '40 days');
INSERT INTO private.push_binding_revocations(id,user_id,created_at) VALUES(public.test_uuid(902),public.test_uuid(1),now()-interval '40 days');
SELECT private.invoke_push_dispatch();
SELECT public.test_assert((SELECT count(*)=1 FROM private.push_events WHERE expires_at < now()-interval '30 days'),'event retention cleanup bounded to 500 per invocation');
SELECT public.test_assert(NOT EXISTS(SELECT FROM public.push_devices WHERE id=public.test_uuid(900)),'stale devices removed after retention');
SELECT public.test_assert(NOT EXISTS(SELECT FROM private.push_binding_revocations WHERE id=public.test_uuid(902)),'old revocation receipts removed after retention');
SELECT private.invoke_push_dispatch();
SELECT public.test_assert(NOT EXISTS(SELECT FROM private.push_events WHERE expires_at < now()-interval '30 days'),'next cleanup finishes retained event backlog');
SET ROLE authenticated;
SELECT public.test_actor(1);
SELECT public.register_push_device(public.test_uuid(201),public.test_uuid(341),'parent-concurrent-token-abcdefghijklmnopqrstuvwxyz');
RESET ROLE;
INSERT INTO public.course_announcements(id,course_id) VALUES(public.test_uuid(90),public.test_uuid(11)),(public.test_uuid(91),public.test_uuid(11));
DO $$ DECLARE c JSONB;BEGIN c:=public.claim_push_deliveries();
 PERFORM public.test_assert(jsonb_array_length(c)=2,'two real deliveries available for concurrency test');
 UPDATE private.push_deliveries SET state='pending',attempts=0,lease_id=NULL,lease_until=NULL,available_at=now()
 WHERE id IN(SELECT (value->>'deliveryId')::UUID FROM jsonb_array_elements(c));END $$;
CREATE TABLE public.test_claims(name TEXT PRIMARY KEY, claim JSONB);
SELECT count(*) AS passed_assertions FROM public.test_results;
