-- V28: Club Management System
-- Adds support for club registration with Stripe Connect,
-- club-to-coach relationships, and club invitation codes

-- ============================================
-- 1. Clubs Table
-- ============================================
CREATE TABLE clubs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_user_id UUID NOT NULL UNIQUE REFERENCES users(id),
    
    -- Basic info
    name VARCHAR(255) NOT NULL,
    description TEXT,
    logo_url VARCHAR(500),
    website VARCHAR(255),
    phone VARCHAR(50),
    email VARCHAR(255),
    address TEXT,
    city VARCHAR(100),
    
    -- Stripe Connect fields
    stripe_account_id VARCHAR(255),
    stripe_onboarding_complete BOOLEAN NOT NULL DEFAULT FALSE,
    stripe_charges_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    stripe_payouts_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- Company/Business info for invoicing (required for clubs)
    company_name VARCHAR(255),
    company_cui VARCHAR(20),
    company_reg_number VARCHAR(50),
    company_address TEXT,
    bank_account VARCHAR(50),
    bank_name VARCHAR(100),
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_clubs_owner ON clubs(owner_user_id);
CREATE INDEX idx_clubs_name ON clubs(name);
CREATE INDEX idx_clubs_city ON clubs(city);
CREATE INDEX idx_clubs_stripe_account ON clubs(stripe_account_id);

-- ============================================
-- 2. Club Sports (many-to-many)
-- ============================================
CREATE TABLE club_sports (
    club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    sport_id UUID NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
    PRIMARY KEY (club_id, sport_id)
);

CREATE INDEX idx_club_sports_club ON club_sports(club_id);
CREATE INDEX idx_club_sports_sport ON club_sports(sport_id);

-- ============================================
-- 3. Club Coaches (many-to-many)
-- ============================================
CREATE TABLE club_coaches (
    club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    coach_profile_id UUID NOT NULL REFERENCES coach_profiles(id) ON DELETE CASCADE,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE, INACTIVE, PENDING
    PRIMARY KEY (club_id, coach_profile_id)
);

CREATE INDEX idx_club_coaches_club ON club_coaches(club_id);
CREATE INDEX idx_club_coaches_coach ON club_coaches(coach_profile_id);
CREATE INDEX idx_club_coaches_status ON club_coaches(status);

-- ============================================
-- 4. Club Invitation Codes Table
-- ============================================
CREATE TABLE club_invitation_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(50) NOT NULL UNIQUE,
    club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    used_by_coach_id UUID REFERENCES coach_profiles(id),
    used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE,
    max_uses INTEGER NOT NULL DEFAULT 1,
    current_uses INTEGER NOT NULL DEFAULT 0,
    notes VARCHAR(500),
    coach_name_hint VARCHAR(100)  -- Optional hint for expected coach name
);

CREATE INDEX idx_club_invitation_codes_code ON club_invitation_codes(code);
CREATE INDEX idx_club_invitation_codes_club ON club_invitation_codes(club_id);
CREATE INDEX idx_club_invitation_codes_used_by ON club_invitation_codes(used_by_coach_id);

-- ============================================
-- 5. Comments for documentation
-- ============================================
COMMENT ON TABLE clubs IS 'Sports clubs/organizations that can manage coaches and courses';
COMMENT ON COLUMN clubs.owner_user_id IS 'User with CLUB role who owns this club';
COMMENT ON COLUMN clubs.stripe_account_id IS 'Stripe Connect Express account ID for receiving payments';
COMMENT ON COLUMN clubs.company_cui IS 'Company CUI/CIF for invoicing (required for Stripe)';

COMMENT ON TABLE club_sports IS 'Sports offered by each club';
COMMENT ON TABLE club_coaches IS 'Coaches associated with each club (many-to-many)';
COMMENT ON COLUMN club_coaches.status IS 'ACTIVE, INACTIVE, or PENDING approval';

COMMENT ON TABLE club_invitation_codes IS 'Invitation codes generated by clubs to invite coaches';
COMMENT ON COLUMN club_invitation_codes.code IS 'Unique invitation code (e.g., XXXX-XXXX)';
COMMENT ON COLUMN club_invitation_codes.max_uses IS 'Maximum number of times this code can be used';
COMMENT ON COLUMN club_invitation_codes.coach_name_hint IS 'Optional expected coach name for verification';
