package com.club.triathlon.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.FetchType
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.Table
import java.time.OffsetDateTime

/**
 * Invitation code generated by a Club to invite coaches to join.
 * When a coach registers with this code, they become associated with the club.
 */
@Entity
@Table(name = "club_invitation_codes")
open class ClubInvitationCode : BaseEntity() {

    @Column(name = "code", nullable = false, unique = true, length = 50)
    lateinit var code: String

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "club_id", nullable = false)
    lateinit var club: Club

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "used_by_coach_id")
    var usedByCoach: CoachProfile? = null

    @Column(name = "used_at")
    var usedAt: OffsetDateTime? = null

    @Column(name = "created_at", nullable = false)
    lateinit var createdAt: OffsetDateTime

    @Column(name = "expires_at")
    var expiresAt: OffsetDateTime? = null

    @Column(name = "max_uses", nullable = false)
    var maxUses: Int = 1

    @Column(name = "current_uses", nullable = false)
    var currentUses: Int = 0

    @Column(name = "notes", length = 500)
    var notes: String? = null

    @Column(name = "coach_name_hint", length = 100)
    var coachNameHint: String? = null

    /**
     * Check if this invitation code is still valid for use
     */
    fun isValid(): Boolean {
        if (currentUses >= maxUses) return false
        if (expiresAt != null && OffsetDateTime.now().isAfter(expiresAt)) return false
        return true
    }

    /**
     * Check if this code has been fully used
     */
    fun isFullyUsed(): Boolean = currentUses >= maxUses

    /**
     * Check if this code has expired
     */
    fun isExpired(): Boolean = expiresAt != null && OffsetDateTime.now().isAfter(expiresAt)

    /**
     * Mark this code as used by a coach
     */
    fun markUsed(coach: CoachProfile) {
        this.currentUses++
        if (this.maxUses == 1) {
            this.usedByCoach = coach
            this.usedAt = OffsetDateTime.now()
        }
    }
}
