ALTER TABLE public.locations
  DROP CONSTRAINT locations_type_check,
  ADD CONSTRAINT locations_type_check CHECK (type IN (
    'POOL', 'INDOOR_POOL', 'OUTDOOR_POOL', 'OPEN_WATER',
    'TRACK', 'FOOTBALL_FIELD', 'BASKETBALL_COURT', 'TENNIS_COURT',
    'PADEL_COURT', 'VOLLEYBALL_COURT', 'HANDBALL_COURT', 'MULTISPORT_COURT', 'STADIUM',
    'GYM', 'FITNESS_GYM', 'SPORTS_HALL', 'CLIMBING_GYM', 'MARTIAL_ARTS_GYM', 'DANCE_STUDIO',
    'PARK', 'RUNNING_TRAIL', 'CYCLING_ROUTE', 'OUTDOOR_AREA', 'OTHER'
  ));
